# Generated by Django 3.1.7 on 2021-02-26 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210226_0819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionManyToOne',
            new_name='QuestionMTM',
        ),
    ]
