# Generated by Django 3.1.7 on 2021-02-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210226_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choiceanswer',
            old_name='quiz',
            new_name='question',
        ),
    ]
