# Generated by Django 3.1.7 on 2021-02-26 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210226_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionMany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(choices=[], max_length=200, verbose_name='Вопрос')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_mtm', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'Вопрос-Выбор',
                'verbose_name_plural': 'Вопросы-Выбор',
            },
        ),
        migrations.RemoveField(
            model_name='questionmtm',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='ChoiceAnswer',
        ),
        migrations.DeleteModel(
            name='QuestionMTM',
        ),
    ]
