# Generated by Django 3.1.7 on 2021-02-26 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210226_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmany',
            name='text',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_answer', to='quiz.questionmany')),
            ],
        ),
    ]
