# Generated by Django 3.1.7 on 2021-02-26 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210226_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmany',
            name='text',
            field=models.CharField(max_length=200, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='questionmany',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_many', to='quiz.quiz'),
        ),
    ]
