# Generated by Django 3.1.7 on 2021-02-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210226_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('type', models.CharField(choices=[('Text', 'text'), ('OneQ', 'one'), ('ManyQ', 'many')], max_length=10, verbose_name='Тип вопроса')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_text', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'Вопрос-Текст',
                'verbose_name_plural': 'Вопросы-Текст',
            },
        ),
        migrations.RemoveField(
            model_name='questionmany',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='QuestionText',
        ),
        migrations.AlterField(
            model_name='choiceanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_answer', to='quiz.question'),
        ),
        migrations.DeleteModel(
            name='QuestionMany',
        ),
    ]
