# Generated by Django 3.1.7 on 2021-02-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20210226_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_options',
            field=models.TextField(blank=True, null=True, verbose_name='Варианты'),
        ),
    ]
