# Generated by Django 3.1.7 on 2021-02-26 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0014_auto_20210226_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='users',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='quiz.question')),
                ('user', models.ManyToManyField(related_name='answer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
