# Generated by Django 3.1.7 on 2021-02-26 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0015_auto_20210226_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
